# Generated by Django 5.2.3 on 2025-08-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rice_disease", "0002_predictionrecord_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionrecord",
            name="location_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
