# Generated by Django 5.2.3 on 2025-08-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rice_disease", "0003_predictionrecord_location_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predictionrecord",
            old_name="location",
            new_name="readable_location",
        ),
        migrations.RemoveField(
            model_name="predictionrecord",
            name="location_name",
        ),
        migrations.AddField(
            model_name="predictionrecord",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="predictionrecord",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
