# Generated by Django 5.2.3 on 2025-09-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rice_disease",
            "0004_rename_location_predictionrecord_readable_location_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictionrecord",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="predictionrecord",
            name="longitude",
        ),
        migrations.AddField(
            model_name="predictionrecord",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
