# Generated by Django 5.2.3 on 2025-09-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rice_disease", "0005_remove_predictionrecord_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionrecord",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="predictionrecord",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
