# Generated by Django 5.2.3 on 2025-10-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rice_disease", "0006_predictionrecord_latitude_predictionrecord_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictionrecord",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="predictionrecord",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="predictionrecord",
            name="readable_location",
        ),
    ]
