# Generated by Django 5.2.3 on 2025-10-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rice_disease", "0009_alter_notification_type_alter_notification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionrecord",
            name="gps_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
