# Generated by Django 5.2.3 on 2025-10-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rice_disease", "0010_predictionrecord_gps_accuracy"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionrecord",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="predictionrecord",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
