# Generated by Django 5.2.3 on 2026-03-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_disease', '0011_predictionrecord_latitude_predictionrecord_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='biological_control',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='chemical_control',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='cultural_control',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
